### ISSUE TITLE
Please clarify breaking changes when releasing a new major version

### ISSUE THREAD

**Issue by robertknight** [karma-runner/karma-chrome-launcher#205]
karma-chrome-launcher was recently bumped from v2.2.0 to v3.0.0. Since this is a semver major change, I expect to see some breaking changes. However none were mentioned in the [CHANGELOG](https://github.com/karma-runner/karma-chrome-launcher/blob/master/CHANGELOG.md).

As a consumer of the library, it would be helpful to know what the breaking changes were in case it is something I need to look out for.

Thank-you for your consideration.

**Comment by johnjbarton** [comment]
Please let me know if you would like to edit the CHANGELOG for future releases.

**Comment by alasdairhurst** [comment]
My thoughts are that it's to do with this commit dropping node 4 support:
https://github.com/karma-runner/karma-chrome-launcher/commit/ae615d0ffcc0e7a9e80aa5a9f80bb81da3853404

I see conventional commits are being used so breaking changes would generally have  BREAKING CHANGE: in the footer

**Comment by rogeriopvl** [comment]
We jumped the major because it's been two years since the last release of karma-chrome-launcher. And although I've been trying my best to maintain the repo during my free time, I don't have publishing permissions, so this version includes a bunch of changes that happened throughout those 2 years. Including that dropping node 4 support commit, although it's not technically a breaking change since it only affects the development environment.

The plan now is to keep the releases more frequent and the changelog updated accordingly.
