### ISSUE TITLE
No output is shown on Chrome browser

### ISSUE THREAD

**Issue by sraparlatmw** [karma-runner/karma-chrome-launcher#56]
<img width="1041" alt="screen shot 2015-08-20 at 7 55 28 pm" src="https://cloud.githubusercontent.com/assets/10406415/9398478/76a2352c-4775-11e5-8b6b-4a1924dd8c87.png">

**Comment by Dignifiedquire** [comment]
What do you expect to be shown?

**Comment by happyvig** [comment]
Hi.,

I expect something like this : 

![image](https://cloud.githubusercontent.com/assets/2972622/16710188/d51b66aa-4643-11e6-8a41-75afb1d33072.png)

The above image is actually the output from a karma reporter. 

How to make karma to show this kind of page automatically always, whenever I run 'karma start'?

**Comment by rogeriopvl** [comment]
@sraparlatmw @happyvig `karma start` just starts the launcher. For the tests to run you need `karma run` in a different terminal (since the one where you ran `karma start` is now blocked). But this will will only output in the console, for html reporting you'll need a different reporter, like the one you posted.
